@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WanderlustParser" as WanderlustParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteActivityCommand" as DeleteActivityCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete -activity 1")
activate LogicManager

LogicManager -> WanderlustParser : parseCommand("delete -activity 1")
activate WanderlustParser

create DeleteCommandParser
WanderlustParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> WanderlustParser
deactivate DeleteCommandParser

WanderlustParser -> DeleteCommandParser : parse(" -activity 1")
activate DeleteCommandParser

create DeleteActivityCommand
DeleteCommandParser -> DeleteActivityCommand
activate DeleteActivityCommand

DeleteActivityCommand --> DeleteCommandParser : d
deactivate DeleteActivityCommand

DeleteCommandParser --> WanderlustParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> WanderlustParser
destroy DeleteCommandParser

WanderlustParser --> LogicManager : d
deactivate WanderlustParser

LogicManager -> DeleteActivityCommand : execute()
activate DeleteActivityCommand

DeleteActivityCommand -> Model : deleteActivity(activityToBeDeleted)
activate Model

Model --> DeleteActivityCommand
deactivate Model

create CommandResult
DeleteActivityCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteActivityCommand
deactivate CommandResult

DeleteActivityCommand --> LogicManager : result
deactivate DeleteActivityCommand

[<--LogicManager
deactivate LogicManager
@enduml
