@startuml
start
:User executes goto command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command causes UI to navigate to specified directory by user])
    if() then ([else])
    :Navigate to specified directory by user;
    else ([already in the directory])
endif

else([goto invalid directory])
:Ui stay on the current directory;
endif
stop
@enduml
