@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyTravelPlanner <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class TravelPlanner
Class ReadOnlyTravelPlanner
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package TravelPlan {
Class TravelPlan
Class ActivityList
Class AccommodationList
Class FriendList
Class UniqueTravelPlanList
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

TravelPlanner .up.|> ReadOnlyTravelPlanner

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" TravelPlanner
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

TravelPlanner *--> "1" UniqueTravelPlanList
UniqueTravelPlanList o--> "*" TravelPlan
TravelPlan *--> Name
TravelPlan *--> "2" WanderlustDate
TravelPlan *--> ActivityList
TravelPlan *--> AccommodationList
TravelPlan *--> FriendList

Name -[hidden]right-> WanderlustDate
WanderlustDate -[hidden]right-> ActivityList
ActivityList -[hidden]right-> AccommodationList
AccommodationList -[hidden]right-> FriendList

ModelManager -->"1" TravelPlan : filtered list
@enduml
