@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyTravelPlanner <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class TravelPlanner
Class ReadOnlyTravelPlanner
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package TravelPlan {
Class TravelPlan
Class ActivityList
Class AccommodationList
Class FriendList
Class UniqueTravelPlanList
}

Package Wishlist {
Class Wishlist
}

Package Activity {
Class UniqueActivityList
}

Package Accommodation {
Class UniqueAccommodationList
}

Package Friend {
Class UniqueFriendList
}

Package Commons {
Class "{abstract}\nTravelPlanObject" as TravelPlanObject
}

Class "{abstract}\nDirectory" as Directory
Class ObservableDirectory

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

TravelPlanner .up.|> ReadOnlyTravelPlanner
ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" TravelPlanner
ModelManager o-right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs
ModelManager -left-> Directory
UserPrefs -[hidden]right-> ReadOnlyTravelPlanner
ObservableDirectory -down-> Directory
ModelManager -left-> ObservableDirectory

TravelPlanner -left-> Wishlist
Wishlist -up-|> Directory
Wishlist -down-> UniqueActivityList

TravelPlanner *--> "1" UniqueTravelPlanList
UniqueTravelPlanList o--> "*" TravelPlan
TravelPlan -up-|> Directory
TravelPlan *--> ActivityList
TravelPlan *--> AccommodationList
TravelPlan *--> FriendList
ActivityList -down-> UniqueActivityList
AccommodationList -down-> UniqueAccommodationList
FriendList -down-> UniqueFriendList

UniqueActivityList o-down-> "*" TravelPlanObject

UniqueAccommodationList o-down-> "*" TravelPlanObject

UniqueFriendList o-down-> "*" TravelPlanObject

ActivityList -[hidden]right-> AccommodationList
AccommodationList -[hidden]right-> FriendList

ModelManager -->"1" TravelPlan : filtered list
ModelManager -right->"4" TravelPlanObject : filtered list
@enduml
