@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface TravelPlannerStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonTravelPlannerStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> TravelPlannerStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonTravelPlannerStorage .left.|> TravelPlannerStorage
JsonTravelPlannerStorage .down.> JsonSerializableTravelPlannerStorage
JsonSerializableTravelPlannerStorage .right.> JsonSerializableTravelPlanner
JsonSerializableTravelPlanner .down.> JsonAdaptedTravelPlan
JsonSerializableTravelPlanner .down.> JsonAdaptedActivity
JsonSerializableTravelPlanner .down.> JsonAdaptedAccommodation
JsonSerializableTravelPlanner .down.> JsonAdaptedFriend
@enduml
