@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class StatusBarFooter
Class CommandBox
Class TravelPlanPanel
Class TravelPlanObjectListPanel
Class TravelPlannerPanel
Class NameCard
Class FriendCard
Class ActivityCard
Class AccommodationCard
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow --> HelpWindow
MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-down-> StatusBarFooter
MainWindow *-down-> TravelPlannerPanel
MainWindow *-down-> TravelPlanObjectListPanel
MainWindow *-down-> TravelPlanPanel

TravelPlannerPanel -down-> NameCard
TravelPlanObjectListPanel -down-> AccommodationCard
TravelPlanObjectListPanel -down-> ActivityCard
TravelPlanObjectListPanel -down-> FriendCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
TravelPlannerPanel --|> UiPart
TravelPlanPanel --|> UiPart
TravelPlanObjectListPanel --|> UiPart
AccommodationCard --|> UiPart
ActivityCard --|> UiPart
FriendCard --|> UiPart
NameCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow -down-|> UiPart

TravelPlannerPanel ..> Model
TravelPlanPanel ..> Model
TravelPlanObjectListPanel ..> Model
TravelPlanObjectListPanel .[hidden].> Model
AccommodationCard ..> Model
ActivityCard ..> Model
FriendCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

AccommodationCard -[hidden]left- FriendCard
ActivityCard -[hidden]left- AccommodationCard
NameCard -[hidden]left- ActivityCard
TravelPlanObjectListPanel -[hidden]left- TravelPlanPanel
TravelPlanPanel -[hidden]left- TravelPlannerPanel
TravelPlannerPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
